# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('product_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUrl',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SyncAlot.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SyncAlot.User'),
        ),
    ]
