# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SyncAlot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraper',
            old_name='xpath',
            new_name='description',
        ),
        migrations.AddField(
            model_name='producturl',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 22, 12, 52, 40, 328820, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producturl',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producturl',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scraper',
            name='price',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scraper',
            name='stock',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
