# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyncAlot', '0002_auto_20160522_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producturl',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 22, 12, 57, 3, 288139)),
        ),
        migrations.AlterField(
            model_name='producturl',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='producturl',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='price',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='stock',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
