# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('SyncAlot', '0003_auto_20160522_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producturl',
            name='last_check',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
