# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyncAlot', '0005_auto_20160522_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='price',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='stock',
        ),
        migrations.AddField(
            model_name='scraper',
            name='import_io_api_key',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='scraper',
            name='import_io_extractor_id',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
